spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      # Book Service Routes
      routes[0]:
        id: BOOK-SERVICE
        uri: lb://BOOK-SERVICE
        predicates[0]: Path=/api/v1/books/**
      # Member Service Routes
      routes[1]:
        id: MEMBER-SERVICE
        uri: lb://MEMBER-SERVICE
        predicates[0]: Path=/api/v1/members/**
      # Loan Service Routes
      routes[2]:
        id: LOAN-SERVICE
        uri: lb://LOAN-SERVICE
        predicates[0]: Path=/api/v1/loans/**
      # Review Service Routes
      routes[3]:
        id: REVIEW-SERVICE
        uri: lb://REVIEW-SERVICE
        predicates[0]: Path=/api/v1/reviews/**
  output:
    ansi:
      enabled: always
server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

