spring:
  application:
    name: config-server
  config:
    import: file:env.properties
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_LINK}
          clone-on-start: true
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
