spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/review_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
